import { Schemas } from "@/utils/serverApi";

export const GenreMap: Record<Schemas["Genre"], string> = {
  action: "Action",
  adventure: "Adventure",
  fantasy: "Fantasy",
  history: "History",
  horror: "Horror",
  music: "Music",
  mystery: "Mystery",
  romance: "Romance",
  science_fiction: "Science fiction",
  thriller: "Thriller",
  war: "War",
  western: "Western",
  action_adventure: "Action adventure",
  animation: "Animation",
  comedy: "Comedy",
  crime: "Crime",
  documentary: "Documentary",
  drama: "Drama",
  family: "Family",
  kids: "Kids",
  news: "News",
  reality: "Reality",
  sci_fi_fantasy: "Sci-fi fantasy",
  soap: "Soap",
  talk: "Talk",
};
